---
config:
  imagesPath: img/characters/
characters:
  game:
    name: ""
    color: white
  player:
    style:
      color: orange
    name: you
  niña:
    style:
      color: blue
    name: Niña
  abuela:
    style:
      color: green
    name: Abuela
  burbuja:
    style:
      color: pink
    name: Burbuja
