screens:
  default:
    background: img/backgrounds/fondonegro.png
  game:
    background: img/backgrounds/map.webp
  parque:
    background: img/backgrounds/park.JPG
  cocina:
    background: img/backgrounds/cocina.png
